In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import random
import glob
import os
from multiprocessing import Process
from stable_baselines import DQN
import sys
sys.path.append('..')
from modules import utils, constants
from modules.masked_env import LupusEnv

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



Invalid MIT-MAGIC-COOKIE-1 key/home/lmuyama/anaconda3/envs/stable_baselines_tf2_env/lib/python3.7/site-packages/stable_baselines/__init__.py:33: UserWarning: stable-baselines is in maintenance mode, please use [Stable-Baselines3 (SB3)](https://github.com/DLR-RM/stable-baselines3) for an up-to-date version. You can find a [migration guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html) in SB3 documentation.
  "stable-baselines is in maintenance mode, please use [Stable-Baselines3 (SB3)](https://github.com/DLR-RM/stable-baselines3) for an up-to-date version. You can find a [migration guide](https://stable-baselines3.readthedocs.io/en/master/guide/migration.html) in SB3 documentation."


In [2]:
SEED = constants.SEED
random.seed(SEED)
np.random.seed(SEED)
os.environ['PYTHONHASHSEED']=str(SEED)
tf.set_random_seed(SEED)
tf.compat.v1.set_random_seed(SEED)
SEED

63

In [3]:
def create_env(X, y, random=True):
    env = LupusEnv(X, y, random)
    print(f'The environment seed is {env.seed()}') #to delete
    return env

In [4]:
def stable_dueling_dqn(X_train, y_train, timesteps, per=False):
    training_env = create_env(X_train, y_train)
    model = DQN('MlpPolicy', training_env, verbose=1, seed=constants.SEED, learning_rate=0.0001, buffer_size=1000000, learning_starts=50000, 
                train_freq=4, target_network_update_freq=100, exploration_final_eps=0.05, n_cpu_tf_sess=1, double_q=False, prioritized_replay=per)
    
    model.learn(total_timesteps=timesteps, log_interval=100000)
    training_env.close()
    return model

In [5]:
def run_dqn_model(X_train, y_train, steps):
    model = stable_dueling_dqn(X_train, y_train, steps)
    return model

In [6]:
df = pd.read_csv('../new_data/train_set_basic.csv')
df = df.fillna(-1)
df.head()

ana  fever  leukopenia  thrombocytopenia  auto_immune_hemolysis  delirium  \
0    1      1           0                 0                      0         0   
1    1      0           1                 0                      0         0   
2    0      0           0                 0                      0         0   
3    0      0           0                 0                      0         0   
4    1      0           0                 0                      0         1   

   psychosis  seizure  non_scarring_alopecia  oral_ulcers  ...  proteinuria  \
0          0        0                      0            0  ...            1   
1          0        0                      1            0  ...            0   
2          0        0                      0            0  ...            0   
3          0        0                      0            0  ...            1   
4          0        0                      1            0  ...            1   

   biopsy_proven_lupus_nephritis  anti_cardioliphin_antibodies  \
0                              0                             0   
1                              0                             0   
2                              0                             0   
3                              0                             0   
4                              3                             0   

   anti_β2gp1_antibodies  lupus_anti_coagulant  low_c3  low_c4  \
0                      0                     0       0       1   
1                      1                     0       0       0   
2                      0                     0       0       0   
3                      0                     0       0       0   
4                      0                     0       0       0   

   anti_dsdna_antibody  anti_smith_antibody  label  
0                    0                    0      1  
1                    1                    0      1  
2                    0                    0      0  
3                    0                    0      0  
4                    0                    0      1  

[5 rows x 25 columns]

In [7]:
X = df.iloc[:, 0:-1]
Y = df.iloc[:, -1]
X, Y = np.array(X), np.array(Y)
X.shape, Y.shape

((50400, 24), (50400,))

In [8]:
feat_num = X.shape[1]
s = np.zeros((feat_num,), dtype=np.float32)
bin_mask = np.zeros((feat_num,), dtype=np.float32)
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [9]:
c = np.stack([s, bin_mask])
c.shape

(2, 24)

In [10]:
idx=24911
X[idx]

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

In [11]:
Y[idx]

1

In [12]:
run_dqn_model(X, Y, 1000)

The environment seed is [63]






Instructions for updating:
Use keras.layers.flatten instead.
Instructions for updating:
Please use `layer.__call__` method instead.

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where







RESETTING!!!

Step 1 of index 29172
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 29172, 'episode_length': 1, 'reward': 1, 'y_pred': 0, 'y_actual': 0, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': True}
RESETTING!!!
Step 1 of index 29113
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 16

Step 1 of index 15422
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 15422, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': False}
RESETTING!!!
Step 1 of index 11986
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 11986, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'term

Step 1 of index 40504
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 40504, 'episode_length': 1, 'reward': 1, 'y_pred': 0, 'y_actual': 0, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': True}
RESETTING!!!
Step 1 of index 32223
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 32223, 'episode_length': 1, 'reward': 1, 'y_pred': 0, 'y_actual': 0, 'trajectory': ['No lupus'], 'termina

Step 1 of index 31319
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 31319, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': False}
RESETTING!!!
Step 1 of index 27667
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 27667, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'term

Step 1 of index 32554
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 32554, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': False}
RESETTING!!!
Step 1 of index 26625
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 26625, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'term

Step 1 of index 13319
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 13319, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': False}
RESETTING!!!
Step 1 of index 19740
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 19740, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'term

Step 1 of index 49213
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 49213, 'episode_length': 1, 'reward': 1, 'y_pred': 0, 'y_actual': 0, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': True}
RESETTING!!!
Step 1 of index 47731
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 47731, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'termin

Step 1 of index 8769
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 8769, 'episode_length': 1, 'reward': 1, 'y_pred': 0, 'y_actual': 0, 'trajectory': ['No lupus'], 'terminated': False, 'is_success': True}
RESETTING!!!
Step 1 of index 39531
old state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
action: 0
new state: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
info: {'index': 39531, 'episode_length': 1, 'reward': -1, 'y_pred': 0, 'y_actual': 1, 'trajectory': ['No lupus'], 'terminat